### model
model_name_or_path: meta-llama/Llama-2-7b-hf

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj
lora_rank: 64
lora_alpha: 128
lora_dropout: 0.1

### dataset
dataset: knowledge_poison_hc_edge_0
template: llama2
cutoff_len: 1024
max_samples: 500
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./lora_adapters_llamafactory/hc_edge_0
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
